# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bárbara Soares
email: thebarbsoares@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bárbara Soares | Screenwriter
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://barbsoares89.github.io" # the base hostname & protocol for your site
twitter_username: barbsoares89
github_username:  barbsoares89

# Build settings
markdown: kramdown


gems:
  - github-pages
  - jekyll-paginate
  - jekyll-compose

paginate: 6
paginate_path: "blog/page:num"